# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 227ede092ca6f9b5328e3527df3bff1ddab165ccb45d2eafce642d9d017db087c6b2f5cd8476a276723960b197bea6e62d8f61a5c580535fa972cf4caa22c3dd

test:
  secret_key_base: 01137442642880c9db0c9954d3740fec1a429bc697c770d040ca160210a89eb796456076926981c54d8753541edce031f7cb918378f6d0acb95b69542ae9d343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
